CREATE TABLE Creator (
    UserID INT PRIMARY KEY NOT NULL,
    Username VARCHAR(50),
    Copyrights_strikes INT DEFAULT 0,
    Subscribers INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (Username),
	CHECK (Subscribers >= 0)
);

CREATE TABLE Video (
    VideoID INT PRIMARY KEY NOT NULL,
    UserID INT,
    Video VARCHAR(200),
    Views INT DEFAULT 0,
    Likes INT DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES Creator(UserID)  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Comments (
    CommentID INT PRIMARY KEY NOT NULL,
    UserID INT,
    VideoID INT,
    FK_CommentID INT,
    Content VARCHAR(200),
    FOREIGN KEY (UserID) REFERENCES Creator(UserID)  ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (VideoID) REFERENCES Video(VideoID)  ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FK_CommentID) REFERENCES Comments(CommentID)  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Playlist (
    PlaylistID INT PRIMARY KEY NOT NULL,
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES Creator(UserID)  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PlaylistVideo (
    PlaylistID INT,
    VideoID INT,
    PRIMARY KEY (PlaylistID, VideoID),
    FOREIGN KEY (PlaylistID) REFERENCES Playlist(PlaylistID)  ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (VideoID) REFERENCES Video(VideoID)  ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Subscribe (
    SubscriberID INT,
    SubscribeeID INT max (99999999),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SubscriberID, SubscribeeID),
    FOREIGN KEY (SubscriberID) REFERENCES Creator(UserID)  ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (SubscribeeID) REFERENCES Creator(UserID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Advertise (
    AdvertiserID INT PRIMARY KEY NOT NULL,
	Advertiser VARCHAR(50),
    VideoID INT,
    FOREIGN KEY (VideoID) REFERENCES Video(VideoID)  ON UPDATE CASCADE ON DELETE CASCADE
);